name: plinks-pw
networks:
  plinks-pw:
    name: plinks-pw
services:
  plinks-pw-postgres:
    image: postgres
    hostname: postgres
    container_name: plinks-pw-postgres
    ports: ['${POSTGRES_PORT:?}:5432']
    volumes: ['plinks-pw-postgres:/var/lib/postgresql/data']
    networks: ['plinks-pw']
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      start_period: 10s
volumes:
  monorepo-postgres: